# Use root/example as user/password credentials
# Run docker-compose -f mysql-stack.yml up
version: '3.1'

services:
  postgresql:
    image: postgres:11.17-alpine
    volumes:
      - ./database-data/postgresql-11.17:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=admin
    ports:
      - '5432:5432'